# Generated by Django 2.2.1 on 2020-01-22 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
