# Generated by Django 2.2.1 on 2020-01-22 09:57

from django.db import migrations, models
import school.models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='approach',
            name='image',
            field=models.ImageField(default='a', upload_to=school.models.rename),
            preserve_default=False,
        ),
    ]
