# Generated by Django 2.2.1 on 2020-01-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_approach_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('details', models.CharField(max_length=100000)),
                ('date', models.DateField()),
            ],
        ),
    ]
