# Generated by Django 2.2.1 on 2020-01-22 10:58

from django.db import migrations, models
import school.models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.ImageField(default='a', upload_to=school.models.rename_event),
            preserve_default=False,
        ),
    ]
