# Generated by Django 2.2.1 on 2020-01-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_group_images_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_images',
            name='name',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='id',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='name',
        ),
        migrations.AddField(
            model_name='group_images',
            name='group_name',
            field=models.CharField(default=1, max_length=264),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groups',
            name='group_name',
            field=models.CharField(default='1', max_length=264, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
