# Generated by Django 2.2.1 on 2020-01-24 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20200124_1502'),
    ]

    operations = [
        migrations.DeleteModel(
            name='group_images',
        ),
        migrations.DeleteModel(
            name='groups',
        ),
    ]
