# Generated by Django 3.0.2 on 2020-01-26 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_group_images_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approach',
            name='details',
        ),
        migrations.RemoveField(
            model_name='events',
            name='details',
        ),
    ]
