# Generated by Django 3.0.2 on 2020-01-26 06:01

from django.db import migrations, models
import school.models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20200126_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=264)),
                ('details', models.TextField(max_length=100000)),
                ('image', models.ImageField(upload_to=school.models.rename_blog)),
            ],
        ),
    ]
