# Generated by Django 2.2.1 on 2020-01-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=100000)),
                ('mobile_number', models.CharField(max_length=264)),
                ('email', models.CharField(max_length=264)),
            ],
        ),
    ]
