# Generated by Django 2.2.1 on 2020-01-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_about_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='school_tiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=264)),
                ('details', models.TextField(max_length=100000)),
            ],
        ),
        migrations.AlterModelOptions(
            name='about_us',
            options={'verbose_name_plural': 'About_Us'},
        ),
        migrations.AlterModelOptions(
            name='approach',
            options={'verbose_name_plural': 'Approach'},
        ),
        migrations.AlterModelOptions(
            name='blogs',
            options={'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='contact_us',
            options={'verbose_name_plural': 'Contact_Us'},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='group_images',
            options={'verbose_name_plural': 'Group_Images'},
        ),
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name_plural': 'Groups'},
        ),
    ]
