# Generated by Django 2.2.1 on 2020-01-29 16:00

from django.db import migrations, models
import school.models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_auto_20200127_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=school.models.rename_carousel)),
                ('title', models.CharField(max_length=264)),
                ('details', models.TextField(max_length=100000)),
            ],
            options={
                'verbose_name_plural': 'Carousel',
            },
        ),
        migrations.AlterModelOptions(
            name='school_tiles',
            options={'verbose_name_plural': 'School_Tiles'},
        ),
    ]
